---
# tasks/java/Alpine.yml file for ansible-nifi
- name: install java (alpine)
  block:
    - name: set java version
      set_fact:
        java_version: "{{ (java_version|string == '8' or java_version|string == '1.8.0') | ternary('1.8', java_version) }}"
      tags: [java, zookeeper]

    - name: install java {{ java_version }}
      apk:
        name: "{{ (java_version|string == '1.8') | ternary('openjdk8-jre-base', 'openjdk11-jre-headless') }}"
        state: present
      when: ansible_os_family == "Alpine"
      tags: [java, zookeeper]

    - name: set java_home
      set_fact:
        java_home: "{{ '/usr/lib/jvm/java-{{ java_version }}-openjdk' | realpath }}"
      tags: [java, zookeeper]

    - name: set default java alternative
      file:
        src: "{{ java_home }}"
        dest: /usr/lib/jvm/default-jvm
        owner: root
        group: root
        state: link
      tags: [java, zookeeper]
  when: ansible_os_family == "Alpine"
