---
# tasks/main/Debian.yml file for ansible-nifi
- name: install dependencies and do basic setup (debian)
  block:
    - name: install base dependencies
      apt:
        name: ["iproute2", "unzip", "procps", "python3", "python3-pip", "python3-apt", "python3-psutil", "software-properties-common"]
        state: present
      tags: [always]

    - name: set default python alternative
      alternatives:
        link: /usr/bin/python
        name: python
        path: /usr/bin/python3
      tags: [always]

    - name: install supervisor
      apt:
        name: supervisor
        state: present
      when: ansible_virtualization_type == "Docker"
      tags: [always]

    - name: set package_facts
      package_facts:
        manager: auto
      tags: [always]

    - name: set supervisor_version
      set_fact:
        supervisor_version: "{{ packages.supervisor[0].version }}"
        cacheable: yes
      tags: [always]

    - name: use python 2 (supervisor < 3.5.x)
      lineinfile:
        dest: "{{ item }}"
        regexp: '^#!\/usr\/bin\/python'
        line: '#!/usr/bin/python2'
      with_items: ["/usr/bin/supervisord", "/usr/bin/supervisorctl"]
      when: supervisor_version is version("3.5.0", "<")
      tags: [always]
  when: ansible_os_family == "Debian"
